; CDDL schema to encode objects like defined in https://github.com/hello-nrfcloud/proto-map/blob/saga/lwm2m/14202.xml
; depends on lwm2m_senml definitions

state_of_charge = {
	bn => "14202/0/",        ; Custom Environment information object
	n => "0",                ; State of Charge ID
	vi => int .size 1,       ; State of Charge value
	bt => int .size 8        ; UNIX timestamp in milliseconds
}
voltage = {
	n => "1",                ; Voltage Resource ID
	vf => float,             ; Battery voltage in Volt.
}
current = {
	n => "2",                ; Current Resource ID
	vf => float,             ; Battery current in mA.
}
temperature = {
	n => "3",                ; Temperature Resource ID
	vf => float,             ; Battery temperature in degrees Celsius.
}
time_to_full = {
	n => "4",                ; Time to full Resource ID
	vf => int .size 8,       ; Time to full in seconds.
}
time_to_empty = {
	n => "5",                ; Time to empty Resource ID
	vf => int .size 8,       ; Time to empty in seconds.
}

bat-object = [
	state_of_charge,
	voltage,
	temperature,
]
