FROM zephyrprojectrtos/ci:v0.27.4 as base

ENV DEBIAN_FRONTEND=noninteractive

RUN <<EOT
    apt-get -y update
    apt-get -y upgrade
    apt-get -y install ruby
EOT

# Prepare image with a ready to use build environment
ADD . /workdir
WORKDIR /workdir
RUN west init -l . && west update --narrow -o=--depth=1
