# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  projects:
    - name: nrf
      url: git@github.com:bjda/fw-nrfconnect-nrf.git
      revision: thingy91x_board
      import: true
