; Define the basic structure of the JSON object
app-object = {
    ? "nrfcloud_mqtt_topic_prefix": tstr,
    ? "pairing": pairing-type,
    "lwm2m": lwm2m-map
}

; Define the pairing object with nested topics
pairing-type = {
    "state": tstr,
    "topics": {
        "d2c": tstr,
        "c2d": tstr
    }
}

lwm2m-map = {
  ? "14240:1.0": led,
  ? "14301:1.0": config
}

led = {
  "0": led_inner_object
}

led_inner_object = {
  "0": int .size 4,
  "1": int .size 4,
  "2": int .size 4,
  "99": int .size 8
}

config = {
  "0": config_inner_object
}

config_inner_object = {
  "0": int .size 8,
  "1": bool,
  "99": int .size 8
}
