# Publish latest documentation on push to main
name: Publish latest documentation on push

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  deploy:
    permissions:
      contents: write
    uses: ./.github/workflows/docs-build-and-publish-zooomin.yml
    with:
      documentation_tag: "latest"
      publish_to_prod: true
      publish_to_dev: true
    secrets: inherit
