name: Publish symbol files to Memfault

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Release version to publish, e.g. "v1.1.0"

jobs:
  publish:
    environment: production

    name: Publish firmware bundles to nRF Cloud

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - run: npm i @octokit/rest

      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install memfault-cli

      - run: node .github/workflows/fetch-release-assets.mjs ${{ inputs.version }}

      - name: Publish oob symbol files
        run: |
          source venv/bin/activate
          memfault \
              --org-token ${{ secrets.MEMFAULT_ORGANIZATION_TOKEN }} \
              --org ${{ vars.MEMFAULT_ORGANIZATION_SLUG }} \
              --project ${{ vars.MEMFAULT_PROJECT_SLUG }} \
              upload-mcu-symbols \
              --software-type hello.nrfcloud.com \
              --software-version ${{ inputs.version }} \
              hello.nrfcloud.com-${{ inputs.version }}-thingy91x-nrf91.elf

      - name: Publish oob-debug symbol files
        run: |
          source venv/bin/activate
          memfault \
              --org-token ${{ secrets.MEMFAULT_ORGANIZATION_TOKEN }} \
              --org ${{ vars.MEMFAULT_ORGANIZATION_SLUG }} \
              --project ${{ vars.MEMFAULT_PROJECT_SLUG }} \
              upload-mcu-symbols \
              --software-type hello.nrfcloud.com \
              --software-version ${{ inputs.version }}+debug \
              hello.nrfcloud.com-${{ inputs.version }}+debug-thingy91x-nrf91.elf
