name: Build and Test

on:
  workflow_dispatch:
    inputs:
      run_fota_tests:
        type: boolean
        required: true
        default: true
      run_fullmfwfota_test:
        type: boolean
        required: true
        default: false
      run_dfu_tests:
        type: boolean
        required: true
        default: true
      run_connectivity_bridge_tests:
        type: boolean
        required: true
        default: true
      run_wifi_location_tests:
        type: boolean
        required: true
        default: true
      run_modem_trace_tests:
        type: boolean
        required: true
        default: true
      run_ppk_tests:
        type: boolean
        required: true
        default: false
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_bl_update: true
  dfu_check:
    uses: ./.github/workflows/dfu_check.yml
    needs: build
    secrets: inherit
    with:
      artifact_fw_version: ${{ needs.build.outputs.version }}
      artifact_run_id: ${{ needs.build.outputs.run_id }}
  test:
    permissions:
      contents: write
    uses: ./.github/workflows/on_target.yml
    needs: build
    secrets: inherit
    with:
      artifact_fw_version: ${{ needs.build.outputs.version }}
      artifact_run_id: ${{ needs.build.outputs.run_id }}
      run_fota_tests: >-
        ${{
          github.event_name == 'schedule' ||
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.run_fota_tests == 'true')
        }}
      run_fullmfwfota_test: >-
        ${{
          github.event_name == 'schedule' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.run_fullmfwfota_test == 'true')
        }}
      run_dfu_tests: >-
        ${{
          github.event_name == 'schedule' ||
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.run_dfu_tests == 'true')
        }}
      run_connectivity_bridge_tests: >-
        ${{
          github.event_name == 'schedule' ||
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.run_connectivity_bridge_tests == 'true')
        }}
      run_wifi_location_tests: >-
        ${{
            github.event_name == 'schedule' ||
            github.event_name == 'push' ||
            (github.event_name == 'workflow_dispatch' && github.event.inputs.run_wifi_location_tests == 'true')
        }}
      run_modem_trace_tests: >-
        ${{
          github.event_name == 'schedule' ||
          github.event_name == 'push' ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.run_modem_trace_tests == 'true')
        }}
      run_ppk_tests: >-
        ${{
            github.event_name == 'schedule' ||
            (github.event_name == 'workflow_dispatch' && github.event.inputs.run_ppk_tests == 'true')
        }}
