name: Build and Test

on:
  workflow_dispatch:
    inputs:
      pytest_marker:
        type: string
        required: false
        default: -m "not slow"

  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      build_bl_update: true
  dfu_check:
    uses: ./.github/workflows/dfu_check.yml
    needs: build
    secrets: inherit
    with:
      artifact_fw_version: ${{ needs.build.outputs.version }}
      artifact_run_id: ${{ needs.build.outputs.run_id }}
  test:
    permissions:
      contents: write
    uses: ./.github/workflows/on_target.yml
    needs: build
    secrets: inherit
    with:
      artifact_fw_version: ${{ needs.build.outputs.version }}
      artifact_run_id: ${{ needs.build.outputs.run_id }}
      pytest_marker: ${{ inputs.pytest_marker || (github.event_name == 'schedule' && '') || (github.event_name == 'push' && '-m "not slow"') }}
